### ISSUE TITLE
notification icon

### ISSUE THREAD

**Issue by rnj2541** [TeleTux/TeleTux#1]
The notification icon is a bit small, please correct it.thx for support

**Comment by Yasin-Kiyani** [comment]
Thanks for your evaluation.  I will definitely solve the problem

**Comment by Yasin-Kiyani** [comment]
> The notification icon is a bit small, please correct it.thx for support

Thanks for your evaluation.  I will definitely solve the problem

**Comment by rnj2541** [comment]
> Thanks for your evaluation. I will definitely solve the problem

thx sir

**Comment by RasolShakeri** [comment]
this is great! I hope we will see progress and optimization of the program.

**Comment by herotux** [comment]
Fixed c31ff238daf849d4ce75d9b6f507d8af47a5f62e
