### ISSUE TITLE
فونت «وزیر متن» 

### ISSUE THREAD

**Issue by neesti** [TeleTux/TeleTux#29]
سلام. 

چنانکه می‌دانید فونت «وزیر» در تازه‌ترین به‌روزرسانی‌هایش به فونت «وزیر متن» تغییر نام داده است و کلی هم بهبود داشته است. 
اگر ممکن است در به‌روزرسانی بعدی تلِتاکس از جدیدترین نسخهٔ «وزیر متن» استفاده بفرمایید. 

https://github.com/rastikerdar/vazirmatn/releases

**Comment by herotux** [comment]
نسخه جدید با تلتاکس سازگاری ندارد
