### ISSUE TITLE
قابلیت ا

### ISSUE THREAD

**Issue by Tobenever** [TeleTux/TeleTux#42]
داداش این گزینه در تلگراف ..توربو ...بیگرام هست شماهم روی این فعال کنی حیف کامل نباش
داداش یک سوال اگر میشه مثل تلگراف یا بیگرام یا توربوگرام یا  غیره تعداد ارسال را 100 به 300 کنی خیلی خوبه

**Comment by herotux** [comment]
دوست عزیز این issue عنوان و متن مناسبی ندارد .
